[[kv_namespaces]]
binding = "ARTICLE_DATA_BINDING"
id = "d4ec98da9c4a4793bdac872e4c7ff5a4"


name = "my-worker"
type = "javascript"

[account]
id = "d4ec98da9c4a4793bdac872e4c7ff5a4"

[env.production]
workers_dev = false
route = "example.com/*"

[env.development]
workers_dev = true